INSERT INTO Types (Type, Kind)
VALUES	('NOTIFICATION_MONA_TRADESCIENCE',	'KIND_NOTIFICATION'),
		('NOTIFICATION_MONA_RESEARCHREWARD','KIND_NOTIFICATION');
INSERT INTO Notifications (NotificationType, SeverityType, ExpiresEndofTurn, AutoActive, ShowIconSinglePlayer, GroupType)
VALUES	('NOTIFICATION_MONA_TRADESCIENCE',	'MID',	1,1,1,'NOTIFICATION_MONA_TRADESCIENCE'	),
		('NOTIFICATION_MONA_RESEARCHREWARD','MID',	1,1,1,'NOTIFICATION_MONA_RESEARCHREWARD'	);